'use strict';

// ── PRESET RANGES ─────────────────────────────────────────────────────────────
// Self-contained — no dependency on app.js.
// state format mirrors prb_state: { "POS_sitId": { "handKey": actionId } }
// actionId: 1=Raise/Open  2=Call/Limp  3=3-Bet  4=Fold

function _buildPresetState(def) {
  const state = {};
  for (const [sk, actions] of Object.entries(def)) {
    const cell = {};
    for (const [aid, hands] of Object.entries(actions)) {
      for (const h of hands) cell[h] = parseInt(aid, 10);
    }
    state[sk] = cell;
  }
  return state;
}

const PRESETS = [

  // ── DÉBUTANT ────────────────────────────────────────────────────────────────
  {
    id:      'beginner',
    label:   'Débutant',
    labelEN: 'Beginner',
    desc:    'Paires 77+, broadways — ranges serrées et claires.',
    descEN:  '77+ pairs, broadways — tight and clear ranges.',
    state: _buildPresetState({
      BTN_open:      { 1: ['AA','KK','QQ','JJ','TT','99','88','77',
                           'AKs','AQs','AJs','ATs',
                           'AKo','AQo','AJo',
                           'KQs','KJs','QJs'] },
      CO_open:       { 1: ['AA','KK','QQ','JJ','TT','99','88',
                           'AKs','AQs','AJs','ATs',
                           'AKo','AQo',
                           'KQs'] },
      HJ_open:       { 1: ['AA','KK','QQ','JJ','TT','99',
                           'AKs','AQs','AJs','ATs',
                           'AKo','AQo',
                           'KQs'] },
      UTG_open:      { 1: ['AA','KK','QQ','JJ','TT',
                           'AKs','AQs','AJs',
                           'AKo','AQo'] },
      SB_open_hu:    { 1: ['AA','KK','QQ','JJ','TT','99','88','77','66',
                           'AKs','AQs','AJs','ATs','A9s','A8s',
                           'AKo','AQo','AJo','ATo',
                           'KQs','KJs','QJs'] },
      SB_open_multi: { 1: ['AA','KK','QQ','JJ','TT','99','88',
                           'AKs','AQs','AJs','ATs',
                           'AKo','AQo','AJo',
                           'KQs'] },
      SB_vs_raise:   { 3: ['AA','KK','QQ','JJ','AKs','AKo'] },
      BB_vs_open:    { 3: ['AA','KK','QQ','AKs','AKo'],
                       2: ['JJ','TT','99','AQs','AJs','ATs','AQo'] },
      BB_vs_raise:   { 3: ['AA','KK','QQ','JJ','AKs','AKo'] },
      BTN_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo'] },
      CO_vs_raise:   { 3: ['AA','KK','QQ','AKs','AKo'] },
      HJ_vs_raise:   { 3: ['AA','KK','QQ','AKs','AKo'] },
      UTG_vs_raise:  { 3: ['AA','KK','AKs'] },
      BTN_vs_limp:   { 1: ['AA','KK','QQ','JJ','TT','99','88',
                           'AKs','AQs','AJs','ATs',
                           'AKo','AQo',
                           'KQs'] },
      CO_vs_limp:    { 1: ['AA','KK','QQ','JJ','TT','99',
                           'AKs','AQs','AJs',
                           'AKo','AQo',
                           'KQs'] },
      HJ_vs_limp:    { 1: ['AA','KK','QQ','JJ','TT',
                           'AKs','AQs',
                           'AKo','AQo'] },
      UTG_vs_limp:   { 1: ['AA','KK','QQ','JJ','TT',
                           'AKs','AKo'] },
      BB_vs_limp:    { 1: ['AA','KK','QQ','JJ','TT','99','88',
                           'AKs','AQs','AJs','ATs',
                           'AKo','AQo','AJo',
                           'KQs','KJs'] },
    }),
  },

  // ── SMALL BALL (Negreanu) ────────────────────────────────────────────────────
  {
    id:      'smallball',
    label:   'Small Ball',
    labelEN: 'Small Ball',
    desc:    'Suited connectors larges, style Negreanu exploitatif.',
    descEN:  'Wide suited connectors, Negreanu exploitative style.',
    state: _buildPresetState({
      BTN_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs','K9s','QJs','QTs','JTs','J9s',
        'T9s','T8s','98s','97s','87s','86s','76s','75s','65s','64s','54s',
        'KQo','KJo','KTo','QJo','QTo','JTo',
      ]},
      CO_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','QJs','QTs','JTs','J9s',
        'T9s','T8s','98s','87s','76s','65s','54s',
        'KQo','KJo','QJo',
      ]},
      HJ_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','QJs','QTs','JTs',
        'T9s','T8s','98s','87s','76s','65s',
        'KQo','KJo','QJo',
      ]},
      UTG_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77',
        'AKs','AQs','AJs','ATs','A9s','A8s','A5s','A4s',
        'AKo','AQo','AJo',
        'KQs','KJs','QJs','JTs','T9s','98s','87s',
        'KQo',
      ]},
      SB_open_hu: {
        1: [
          'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
          'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
          'AKo','AQo','AJo','ATo','A9o','A8o','A7o',
          'KQs','KJs','KTs','K9s','K8s','QJs','QTs','Q9s',
          'JTs','J9s','T9s','T8s','98s','97s','87s','76s','65s','54s',
          'KQo','KJo','KTo','K9o','QJo','QTo','JTo',
        ],
        2: ['A6o','A5o','A4o','A3o','A2o','K7o','K6o','Q9o','J9o','T8o','97o','86o','75o'],
      },
      SB_open_multi: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s','A8s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','QJs','JTs',
        'T9s','T8s','98s','87s','76s','65s',
        'KQo','KJo',
      ]},
      SB_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s','A4s'],
                      2: ['TT','99','AJs','ATs','KQs'] },
      BB_vs_open:   { 3: ['AA','KK','QQ','AKs','AKo','AQs'],
                      2: ['JJ','TT','99','88','77','66','55','44','33','22',
                          'AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
                          'AQo','AJo','ATo',
                          'KQs','KJs','KTs','K9s','QJs','QTs','JTs','J9s',
                          'T9s','T8s','98s','87s','76s','65s','54s',
                          'KQo','KJo','QJo'] },
      BB_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s'],
                      2: ['TT','99','AJs','ATs','KQs','KJs'] },
      BTN_vs_raise: { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s','A4s'] },
      CO_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s'] },
      HJ_vs_raise:  { 3: ['AA','KK','QQ','AKs','AKo','AQs'] },
      UTG_vs_raise: { 3: ['AA','KK','AKs','AKo'] },
      BTN_vs_limp:  { 1: ['AA','KK','QQ','JJ','TT','99','88','77','66','55',
                          'AKs','AQs','AJs','ATs','A9s','A8s',
                          'AKo','AQo','AJo','ATo',
                          'KQs','KJs','KTs','QJs','JTs','T9s','98s','87s',
                          'KQo','KJo','QJo'] },
      CO_vs_limp:   { 1: ['AA','KK','QQ','JJ','TT','99','88','77',
                          'AKs','AQs','AJs','ATs','A9s',
                          'AKo','AQo','AJo',
                          'KQs','KJs','QJs','JTs','KQo'] },
      HJ_vs_limp:   { 1: ['AA','KK','QQ','JJ','TT','99','88',
                          'AKs','AQs','AJs','ATs',
                          'AKo','AQo','AJo',
                          'KQs','KJs','QJs','KQo'] },
      UTG_vs_limp:  { 1: ['AA','KK','QQ','JJ','TT','99',
                          'AKs','AQs','AJs',
                          'AKo','AQo',
                          'KQs','KQo'] },
      BB_vs_limp:   { 1: ['AA','KK','QQ','JJ','TT','99','88','77','66',
                          'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A5s','A4s',
                          'AKo','AQo','AJo','ATo',
                          'KQs','KJs','KTs','QJs','JTs','T9s','98s','87s','76s',
                          'KQo','KJo','QJo'] },
    }),
  },

  // ── AVANCÉ (near-GTO) ────────────────────────────────────────────────────────
  {
    id:      'advanced',
    label:   'Avancé',
    labelEN: 'Advanced',
    desc:    'Ranges larges proches GTO — 40%+ au BTN.',
    descEN:  'Wide near-GTO ranges — 40%+ BTN opens.',
    state: _buildPresetState({
      BTN_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s',
        'QJs','QTs','Q9s','Q8s','Q7s',
        'JTs','J9s','J8s','J7s',
        'T9s','T8s','T7s',
        '98s','97s','96s',
        '87s','86s','85s',
        '76s','75s','74s',
        '65s','64s','63s',
        '54s','53s','52s',
        '43s','42s','32s',
        'KQo','KJo','KTo','K9o',
        'QJo','QTo','Q9o',
        'JTo','J9o','J8o',
        'T9o','T8o',
        '98o','97o',
        '87o','86o',
        '76o',
      ]},
      CO_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s',
        'QJs','QTs','Q9s','Q8s',
        'JTs','J9s','J8s',
        'T9s','T8s','T7s',
        '98s','97s','96s',
        '87s','86s','85s',
        '76s','75s',
        '65s','64s',
        '54s','53s',
        'KQo','KJo','KTo','K9o',
        'QJo','QTo','Q9o',
        'JTo','J9o',
        'T9o','T8o',
        '98o','97o',
        '87o',
        '76o',
      ]},
      HJ_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs','K9s','K8s','K7s',
        'QJs','QTs','Q9s','Q8s',
        'JTs','J9s','J8s',
        'T9s','T8s',
        '98s','97s',
        '87s','86s',
        '76s','75s',
        '65s','64s',
        '54s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo','J9o',
        'T9o',
        '98o',
        '87o',
      ]},
      UTG_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s','T8s',
        '98s','97s',
        '87s',
        '76s',
        '65s',
        '54s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo',
        'T9o',
      ]},
      SB_open_hu: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s',
        'JTs','J9s','J8s','J7s','J6s',
        'T9s','T8s','T7s','T6s',
        '98s','97s','96s','95s',
        '87s','86s','85s','84s',
        '76s','75s','74s',
        '65s','64s',
        '54s','53s',
        '43s',
        'KQo','KJo','KTo','K9o','K8o','K7o',
        'QJo','QTo','Q9o','Q8o',
        'JTo','J9o','J8o','J7o',
        'T9o','T8o','T7o',
        '98o','97o','96o',
        '87o','86o',
        '76o','75o',
        '65o',
      ]},
      SB_open_multi: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s',
        'JTs','J9s','J8s',
        'T9s','T8s',
        '98s','97s',
        '87s','86s',
        '76s','75s',
        '65s',
        '54s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo','J9o',
        'T9o',
      ]},
      SB_vs_raise:  { 3: ['AA','KK','QQ','JJ','TT','AKs','AKo','AQs','AQo','A5s','A4s','A3s','A2s','KQs'],
                      2: ['99','88','AJs','ATs','A9s','KJs','KTs','QJs','JTs','T9s'] },
      BB_vs_open:   { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s','A4s','A3s','A2s','KQs'],
                      2: ['TT','99','88','77','66','55','44','33','22',
                          'AQo','AJs','ATs','A9s','A8s','A7s','A6s',
                          'AJo','ATo','A9o',
                          'KJs','KTs','K9s','K8s',
                          'KQo','KJo','KTo',
                          'QJs','QTs','Q9s','Q8s',
                          'JTs','J9s','J8s',
                          'T9s','T8s',
                          '98s','97s',
                          '87s','86s',
                          '76s','75s',
                          '65s','64s',
                          '54s',
                          'QJo','QTo','JTo','T9o'] },
      BB_vs_raise:  { 3: ['AA','KK','QQ','JJ','TT','AKs','AKo','AQs','AQo','A5s','A4s','KQs'],
                      2: ['99','88','77','AJs','ATs','KJs','KTs','QJs','JTs','T9s','98s'] },
      BTN_vs_raise: { 3: ['AA','KK','QQ','JJ','TT','AKs','AKo','AQs','A5s','A4s','A3s','KQs'],
                      2: ['99','AJs','ATs','KJs','JTs'] },
      CO_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s','A4s','KQs'],
                      2: ['TT','99','AJs','ATs'] },
      HJ_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s'],
                      2: ['TT','AJs'] },
      UTG_vs_raise: { 3: ['AA','KK','QQ','JJ','AKs','AKo'] },
      BTN_vs_limp:  { 1: ['AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
                          'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
                          'AKo','AQo','AJo','ATo','A9o','A8o',
                          'KQs','KJs','KTs','K9s','K8s',
                          'QJs','QTs','Q9s','JTs','J9s',
                          'T9s','T8s','98s','97s','87s','86s','76s','75s','65s','54s',
                          'KQo','KJo','KTo','QJo','QTo','JTo','T9o'] },
      CO_vs_limp:   { 1: ['AA','KK','QQ','JJ','TT','99','88','77','66','55',
                          'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A5s',
                          'AKo','AQo','AJo','ATo',
                          'KQs','KJs','KTs','K9s','QJs','QTs','JTs','J9s',
                          'T9s','T8s','98s','87s','76s','65s','54s',
                          'KQo','KJo','QJo','QTo'] },
      HJ_vs_limp:   { 1: ['AA','KK','QQ','JJ','TT','99','88','77',
                          'AKs','AQs','AJs','ATs','A9s','A8s','A5s',
                          'AKo','AQo','AJo','ATo',
                          'KQs','KJs','KTs','QJs','QTs','JTs',
                          'T9s','98s','87s','76s',
                          'KQo','KJo','QJo'] },
      UTG_vs_limp:  { 1: ['AA','KK','QQ','JJ','TT','99','88',
                          'AKs','AQs','AJs','ATs','A9s',
                          'AKo','AQo','AJo',
                          'KQs','KJs','QJs','JTs','T9s',
                          'KQo','KJo'] },
      BB_vs_limp:   { 1: ['AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
                          'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
                          'AKo','AQo','AJo','ATo','A9o',
                          'KQs','KJs','KTs','K9s','K8s',
                          'QJs','QTs','Q9s','JTs','J9s',
                          'T9s','T8s','98s','97s','87s','86s','76s','75s','65s','54s',
                          'KQo','KJo','KTo','QJo','QTo','JTo'] },
    }),
  },
];
