'use strict';

// ── PRESET RANGES ─────────────────────────────────────────────────────────────
// Self-contained — no dependency on app.js.
// state format mirrors prb_state: { "POS_sitId": { "handKey": actionId } }
// actionId: 1=Raise/Open  2=Call/Limp  3=3-Bet  4=Fold

function _buildPresetState(def) {
  const state = {};
  for (const [sk, actions] of Object.entries(def)) {
    const cell = {};
    for (const [aid, hands] of Object.entries(actions)) {
      for (const h of hands) cell[h] = parseInt(aid, 10);
    }
    state[sk] = cell;
  }
  return state;
}

const PRESETS = [

  // ── CONSERVATEUR ─────────────────────────────────────────────────────────────
  // UTG ~12%  HJ ~16%  CO ~22%  BTN ~32%  SB ~35%
  {
    id:      'conservateur',
    label:   'Conservateur',
    labelEN: 'Conservative',
    desc:    'Ranges serrées pour débutants. Facile à jouer et à défendre.',
    descEN:  'Tight ranges for beginners. Easy to play and defend.',
    state: _buildPresetState({

      // ── Opens ─────────────────────────────────────────────────────────────
      BTN_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44',
        'AKs','AQs','AJs','ATs','A9s','A8s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs',
        'KQo','KJo',
        'QJs','JTs','T9s','98s','87s',
      ]},
      BTN_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s',
        'AKo','AQo','AJo','ATo','A9o','A8o',
        'KQs','KJs','KTs',
        'KQo','KJo',
        'QJs','JTs','T9s','98s','87s','76s','65s',
      ]},
      CO_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs',
        'KQo',
        'QJs','JTs',
      ]},
      CO_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44',
        'AKs','AQs','AJs','ATs','A9s','A8s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs',
        'KQo',
        'QJs','JTs','T9s',
      ]},
      HJ_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs',
        'AKo','AQo','AJo',
        'KQs','KJs',
        'QJs',
      ]},
      HJ_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s',
        'AKo','AQo','AJo',
        'KQs','KJs',
        'KQo','QJs','JTs',
      ]},
      UTG_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77',
        'AKs','AQs','AJs','ATs',
        'AKo','AQo','AJo',
        'KQs',
      ]},
      UTG_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s',
        'AKo','AQo','AJo',
        'KQs','KJs',
      ]},
      SB_open_hu: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s',
        'AKo','AQo','AJo','ATo','A9o','A8o',
        'KQs','KJs','KTs',
        'KQo','KJo',
        'QJs','JTs','T9s','98s','87s','76s','65s','54s',
      ]},
      SB_open_hu_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o',
        'KQs','KJs','KTs','K9s',
        'KQo','KJo','KTo',
        'QJs','JTs','T9s','98s','87s','76s','65s','54s','43s',
      ]},
      SB_open_multi: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s',
        'AKo','AQo','AJo',
        'KQs','KJs',
        'QJs',
      ]},
      SB_open_multi_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s','A8s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','QJs',
      ]},

      // ── Vs Raise ──────────────────────────────────────────────────────────
      SB_vs_raise:   { 3: ['AA','KK','QQ','AKs','AKo'] },
      BB_vs_raise:   { 3: ['AA','KK','QQ','JJ','AKs','AKo'] },
      BTN_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo'] },
      CO_vs_raise:   { 3: ['AA','KK','QQ','AKs','AKo'] },
      HJ_vs_raise:   { 3: ['AA','KK','QQ','AKs','AKo'] },
      UTG_vs_raise:  { 3: ['AA','KK','AKs'] },

      // ── Vs Open (BB) ──────────────────────────────────────────────────────
      BB_vs_open: {
        3: ['AA','KK','QQ','AKs','AKo'],
        2: [
          'JJ','TT','99','88','77','66','55','44','33','22',
          'AQs','AJs','ATs','A9s','A8s',
          'AQo','AJo','ATo',
          'KQs','KJs','KTs','QJs','JTs','T9s','98s','87s','76s','65s','54s',
          'KQo','KJo',
        ],
      },

      // ── Vs Limp ───────────────────────────────────────────────────────────
      BTN_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77',
        'AKs','AQs','AJs','ATs',
        'AKo','AQo','AJo',
        'KQs','KJs','QJs',
      ]},
      CO_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88',
        'AKs','AQs','AJs',
        'AKo','AQo',
        'KQs',
      ]},
      HJ_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99',
        'AKs','AQs',
        'AKo','AQo',
      ]},
      UTG_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT',
        'AKs','AKo',
      ]},
      BB_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','QJs','JTs',
      ]},
    }),
  },

  // ── SOLIDE ───────────────────────────────────────────────────────────────────
  // UTG ~18%  HJ ~21%  CO ~28%  BTN ~44%  SB ~55%
  {
    id:      'solide',
    label:   'Solide',
    labelEN: 'Solid',
    desc:    'Ranges équilibrées — standard 6-max 100bb. Recommandé pour joueurs intermédiaires.',
    descEN:  'Balanced ranges — standard 6-max 100bb. Recommended for intermediate players.',
    state: _buildPresetState({

      // ── Opens ─────────────────────────────────────────────────────────────
      BTN_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s',
        'JTs','J9s','J8s','J7s','J6s','J5s','J4s',
        'T9s','T8s','T7s','T6s',
        '98s','97s','96s',
        '87s','86s','85s',
        '76s','75s',
        '65s','64s',
        '54s','53s',
        'KQo','KJo','KTo','K9o','K8o',
        'QJo','QTo','Q9o',
        'JTo','J9o',
        'T9o','T8o',
        '98o',
      ]},
      BTN_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s',
        'JTs','J9s','J8s','J7s','J6s','J5s','J4s',
        'T9s','T8s','T7s','T6s',
        '98s','97s','96s',
        '87s','86s','85s',
        '76s','75s',
        '65s','64s',
        '54s','53s',
        'KQo','KJo','KTo','K9o','K8o',
        'QJo','QTo','Q9o',
        'JTo','J9o',
        'T9o','T8o',
        '98o','87o',
      ]},
      CO_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s',
        'JTs','J9s','J8s',
        'T9s','T8s','T7s',
        '98s','97s',
        '87s','86s',
        '76s',
        '65s',
        '54s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo',
        'A8o',
      ]},
      CO_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s',
        'JTs','J9s','J8s',
        'T9s','T8s','T7s',
        '98s','97s',
        '87s','86s',
        '76s','75s',
        '65s',
        '54s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo','J9o',
        'T9o',
        'A8o','A7o',
      ]},
      HJ_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s','T8s',
        '98s','87s','76s',
        'KQo','KJo','KTo',
        'QJo','QTo',
      ]},
      HJ_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s','T8s',
        '98s','87s','76s','65s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo',
      ]},
      UTG_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s',
        'KQo','KJo',
        'QJo',
      ]},
      UTG_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s','98s',
        'KQo','KJo','KTo',
        'QJo',
      ]},
      SB_open_hu: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s','Q2s',
        'JTs','J9s','J8s','J7s','J6s','J5s','J4s','J3s','J2s',
        'T9s','T8s','T7s','T6s','T5s','T4s','T3s',
        '98s','97s','96s','95s','94s',
        '87s','86s','85s','84s',
        '76s','75s','74s',
        '65s','64s','63s',
        '54s','53s',
        'KQo','KJo','KTo','K9o','K8o','K7o','K6o','K5o','K4o',
        'QJo','QTo','Q9o','Q8o','Q7o','Q6o','Q5o',
        'JTo','J9o','J8o','J7o',
        'T9o','T8o',
        '98o',
      ],
      2: ['A3o','A2o'] },
      SB_open_hu_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o','A3o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s','Q2s',
        'JTs','J9s','J8s','J7s','J6s','J5s','J4s','J3s','J2s',
        'T9s','T8s','T7s','T6s','T5s','T4s','T3s',
        '98s','97s','96s','95s','94s',
        '87s','86s','85s','84s',
        '76s','75s','74s',
        '65s','64s','63s',
        '54s','53s',
        'KQo','KJo','KTo','K9o','K8o','K7o','K6o','K5o','K4o',
        'QJo','QTo','Q9o','Q8o','Q7o','Q6o','Q5o',
        'JTo','J9o','J8o','J7o',
        'T9o','T8o',
        '98o','87o',
      ],
      2: ['A2o','76o'] },
      SB_open_multi: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s','T8s',
        '98s','87s','76s','65s',
        'KQo','KJo',
      ]},
      SB_open_multi_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s','T8s',
        '98s','87s','76s','65s','54s',
        'KQo','KJo','KTo',
      ]},

      // ── Vs Raise ──────────────────────────────────────────────────────────
      SB_vs_raise:   { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s','A4s'],
                       2: ['TT','99','AJs','ATs','KQs'] },
      BB_vs_raise:   { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s'],
                       2: ['TT','99','AJs','ATs','KQs','KJs'] },
      BTN_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s','A4s'] },
      CO_vs_raise:   { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s'] },
      HJ_vs_raise:   { 3: ['AA','KK','QQ','AKs','AKo','AQs'] },
      UTG_vs_raise:  { 3: ['AA','KK','AKs','AKo'] },

      // ── Vs Open (BB) ──────────────────────────────────────────────────────
      BB_vs_open: {
        3: ['AA','KK','QQ','AKs','AKo','AQs'],
        2: [
          'JJ','TT','99','88','77','66','55','44','33','22',
          'AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
          'AQo','AJo','ATo',
          'KQs','KJs','KTs','K9s','QJs','QTs','Q9s','JTs','J9s',
          'T9s','T8s','98s','87s','76s','65s','54s',
          'KQo','KJo','QJo',
        ],
      },

      // ── Vs Limp ───────────────────────────────────────────────────────────
      BTN_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s','A8s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','QJs','JTs','T9s','98s','87s',
        'KQo','KJo','QJo',
      ]},
      CO_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77',
        'AKs','AQs','AJs','ATs','A9s',
        'AKo','AQo','AJo',
        'KQs','KJs','QJs','JTs','KQo',
      ]},
      HJ_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88',
        'AKs','AQs','AJs','ATs',
        'AKo','AQo','AJo',
        'KQs','KJs','QJs','KQo',
      ]},
      UTG_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99',
        'AKs','AQs','AJs',
        'AKo','AQo',
        'KQs','KQo',
      ]},
      BB_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A5s','A4s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','QJs','JTs','T9s','98s','87s','76s',
        'KQo','KJo','QJo',
      ]},
    }),
  },

  // ── EXPERT ───────────────────────────────────────────────────────────────────
  // UTG ~17%  HJ ~21%  CO ~27%  BTN ~51%  SB ~62%
  {
    id:      'expert',
    label:   'Expert',
    labelEN: 'Expert',
    desc:    'Ranges GTO complètes. Pour joueurs avancés — BTN ~51%, UTG ~17%.',
    descEN:  'Full GTO ranges for advanced players — BTN ~51%, UTG ~17%.',
    state: _buildPresetState({

      // ── Opens ─────────────────────────────────────────────────────────────
      BTN_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o','A3o','A2o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s','Q2s',
        'JTs','J9s','J8s','J7s','J6s',
        'T9s','T8s','T7s','T6s',
        '98s','97s','96s',
        '87s','86s','85s',
        '76s','75s',
        '65s','64s',
        '54s','53s',
        '43s','32s',
        'KQo','KJo','KTo','K9o','K8o','K7o',
        'QJo','QTo','Q9o','Q8o',
        'JTo','J9o','J8o',
        'T9o','T8o',
        '98o','97o',
        '87o','76o',
      ]},
      BTN_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o','A3o','A2o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s','Q2s',
        'JTs','J9s','J8s','J7s','J6s',
        'T9s','T8s','T7s','T6s',
        '98s','97s','96s',
        '87s','86s','85s',
        '76s','75s',
        '65s','64s',
        '54s','53s',
        '43s','32s',
        'KQo','KJo','KTo','K9o','K8o','K7o','K6o',
        'QJo','QTo','Q9o','Q8o',
        'JTo','J9o','J8o',
        'T9o','T8o',
        '98o','97o',
        '87o','76o','65o',
      ]},
      CO_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs','K9s','K8s','K7s',
        'QJs','QTs','Q9s','Q8s',
        'JTs','J9s','J8s',
        'T9s','T8s',
        '98s','97s',
        '87s','86s',
        '76s','75s',
        '65s',
        '54s','43s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo',
      ]},
      CO_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s',
        'QJs','QTs','Q9s','Q8s',
        'JTs','J9s','J8s',
        'T9s','T8s',
        '98s','97s',
        '87s','86s',
        '76s','75s',
        '65s',
        '54s','43s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo','J9o',
        'T9o',
      ]},
      HJ_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s','T8s',
        '98s','87s','76s','65s','54s',
        'KQo','KJo',
      ]},
      HJ_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','K8s','K7s',
        'QJs','QTs','Q9s',
        'JTs','J9s',
        'T9s','T8s',
        '98s','87s','76s','65s','54s',
        'KQo','KJo','KTo',
      ]},
      UTG_open: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s','A5s',
        'AKo','AQo',
        'KQs','KJs','KTs',
        'QJs','QTs',
        'JTs','T9s','98s',
      ]},
      UTG_open_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66',
        'AKs','AQs','AJs','ATs','A9s','A5s','A4s',
        'AKo','AQo',
        'KQs','KJs','KTs',
        'QJs','QTs',
        'JTs','T9s','98s',
        'KJo',
      ]},
      SB_open_hu: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o','A3o','A2o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s','Q2s',
        'JTs','J9s','J8s','J7s','J6s','J5s','J4s','J3s','J2s',
        'T9s','T8s','T7s','T6s','T5s','T4s','T3s',
        '98s','97s','96s','95s','94s',
        '87s','86s','85s','84s',
        '76s','75s','74s',
        '65s','64s',
        '54s','53s',
        '43s',
        'KQo','KJo','KTo','K9o','K8o','K7o',
        'QJo','QTo','Q9o','Q8o',
        'JTo','J9o','J8o','J7o',
        'T9o','T8o','T7o',
        '98o','97o','96o',
        '87o','86o',
        '76o','75o',
        '65o',
      ]},
      SB_open_hu_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o','A3o','A2o',
        'KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','K4s','K3s','K2s',
        'QJs','QTs','Q9s','Q8s','Q7s','Q6s','Q5s','Q4s','Q3s','Q2s',
        'JTs','J9s','J8s','J7s','J6s','J5s','J4s','J3s','J2s',
        'T9s','T8s','T7s','T6s','T5s','T4s','T3s',
        '98s','97s','96s','95s','94s',
        '87s','86s','85s','84s',
        '76s','75s','74s',
        '65s','64s',
        '54s','53s',
        '43s',
        'KQo','KJo','KTo','K9o','K8o','K7o','K6o',
        'QJo','QTo','Q9o','Q8o','Q7o',
        'JTo','J9o','J8o','J7o',
        'T9o','T8o','T7o',
        '98o','97o','96o',
        '87o','86o',
        '76o','75o',
        '65o','54o',
      ]},
      SB_open_multi: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s',
        'JTs','J9s','J8s',
        'T9s','T8s',
        '98s','97s',
        '87s','86s',
        '76s','75s',
        '65s',
        '54s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo','J9o',
        'T9o',
      ]},
      SB_open_multi_antes: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs','K9s','K8s','K7s',
        'QJs','QTs','Q9s',
        'JTs','J9s','J8s',
        'T9s','T8s',
        '98s','97s',
        '87s','86s',
        '76s','75s',
        '65s',
        '54s',
        'KQo','KJo','KTo',
        'QJo','QTo',
        'JTo','J9o',
        'T9o','T8o',
      ]},

      // ── Vs Raise ──────────────────────────────────────────────────────────
      SB_vs_raise:   { 3: ['AA','KK','QQ','JJ','TT','AKs','AKo','AQs','AQo','A5s','A4s','A3s','A2s','KQs'],
                       2: ['99','88','AJs','ATs','A9s','KJs','KTs','QJs','JTs','T9s'] },
      BB_vs_raise:   { 3: ['AA','KK','QQ','JJ','TT','AKs','AKo','AQs','AQo','A5s','A4s','KQs'],
                       2: ['99','88','77','AJs','ATs','KJs','KTs','QJs','JTs','T9s','98s'] },
      BTN_vs_raise:  { 3: ['AA','KK','QQ','JJ','TT','AKs','AKo','AQs','A5s','A4s','A3s','KQs'],
                       2: ['99','AJs','ATs','KJs','JTs'] },
      CO_vs_raise:   { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s','A4s','KQs'],
                       2: ['TT','99','AJs','ATs'] },
      HJ_vs_raise:   { 3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s'],
                       2: ['TT','AJs'] },
      UTG_vs_raise:  { 3: ['AA','KK','QQ','JJ','AKs','AKo'] },

      // ── Vs Open (BB) ──────────────────────────────────────────────────────
      BB_vs_open: {
        3: ['AA','KK','QQ','JJ','AKs','AKo','AQs','A5s','A4s','A3s','A2s','KQs'],
        2: [
          'TT','99','88','77','66','55','44','33','22',
          'AQo','AJs','ATs','A9s','A8s','A7s','A6s',
          'AJo','ATo','A9o',
          'KJs','KTs','K9s','K8s',
          'KQo','KJo','KTo',
          'QJs','QTs','Q9s','Q8s',
          'JTs','J9s','J8s',
          'T9s','T8s',
          '98s','97s',
          '87s','86s',
          '76s','75s',
          '65s','64s',
          '54s',
          'QJo','QTo','JTo','T9o',
        ],
      },

      // ── Vs Limp ───────────────────────────────────────────────────────────
      BTN_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o','A8o',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s','JTs','J9s',
        'T9s','T8s','98s','97s','87s','86s','76s','75s','65s','54s',
        'KQo','KJo','KTo','QJo','QTo','JTo','T9o',
      ]},
      CO_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A5s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','K9s','QJs','QTs','JTs','J9s',
        'T9s','T8s','98s','87s','76s','65s','54s',
        'KQo','KJo','QJo','QTo',
      ]},
      HJ_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77',
        'AKs','AQs','AJs','ATs','A9s','A8s','A5s',
        'AKo','AQo','AJo','ATo',
        'KQs','KJs','KTs','QJs','QTs','JTs',
        'T9s','98s','87s','76s',
        'KQo','KJo','QJo',
      ]},
      UTG_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88',
        'AKs','AQs','AJs','ATs','A9s',
        'AKo','AQo','AJo',
        'KQs','KJs','QJs','JTs','T9s',
        'KQo','KJo',
      ]},
      BB_vs_limp: { 1: [
        'AA','KK','QQ','JJ','TT','99','88','77','66','55','44','33','22',
        'AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s',
        'AKo','AQo','AJo','ATo','A9o',
        'KQs','KJs','KTs','K9s','K8s',
        'QJs','QTs','Q9s','JTs','J9s',
        'T9s','T8s','98s','97s','87s','86s','76s','75s','65s','54s',
        'KQo','KJo','KTo','QJo','QTo','JTo',
      ]},
    }),
  },
];
